/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.Estudios;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PC 2
 */
public class Agregar_Estudios extends javax.swing.JFrame {

    public static Estudios estudios = new Estudios();
    
    private String study_name;
    private String study_place;
    private String study_date;
    
    public Agregar_Estudios() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/Icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Studies_Description = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Studies_Place = new javax.swing.JTextField();
        Studies_Date = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        Back_Menu = new javax.swing.JButton();
        End = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingreso de Empleado - Agregar Estudios");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Estudios Realizados");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 104, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Descripción Estudio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 159, -1, -1));

        Studies_Description.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Studies_Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 238, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Instituto de Estudio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 211, -1, -1));

        Studies_Place.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Studies_Place, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 205, 238, 30));

        try {
            Studies_Date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(Studies_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 257, 240, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fecha de Obtención");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 262, -1, -1));

        Back_Menu.setBackground(new java.awt.Color(153, 102, 0));
        Back_Menu.setText("Volver al Menú");
        Back_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Back_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 306, 120, 30));

        End.setBackground(new java.awt.Color(153, 153, 0));
        End.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        End.setText("Ingresar los datos");
        End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndActionPerformed(evt);
            }
        });
        getContentPane().add(End, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 305, 150, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo3.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_MenuActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_Back_MenuActionPerformed

    private void EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndActionPerformed
        try {
            if (Studies_Description.getText().isEmpty() || Studies_Place.getText().isEmpty() || Studies_Date.getText().isEmpty()) {
                throw new NullPointerException("Ha ocurrido un error");
            } else {
                study_name = Studies_Description.getText();
                study_place = Studies_Place.getText();
                study_date = Studies_Date.getText();
            }

            estudios = new Estudios(study_name, study_place, study_date);
            Ingresar_Empleado.studies_info.add(estudios);
            JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            Studies_Description.setText("");
            Studies_Place.setText("");
            Studies_Date.setText("");
        } catch (NullPointerException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Estudios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Estudios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Estudios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Estudios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Estudios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Menu;
    private javax.swing.JButton End;
    private javax.swing.JLabel Fondo;
    private javax.swing.JFormattedTextField Studies_Date;
    private javax.swing.JTextField Studies_Description;
    private javax.swing.JTextField Studies_Place;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
