/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.Empleado;
import Classes.Estudios;
import Classes.Hijo;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import java.util.InputMismatchException;
import java.util.LinkedList;
import javax.swing.JFrame;

/**
 *
 * @author PC 2
 */
public class Ingresar_Empleado extends javax.swing.JFrame {

    public static Empleado empleado;

    public static LinkedList<Empleado> Lista = new LinkedList<Empleado>();

    private static final int year = 2017;

    private String name;
    private String born_year;
    private String born_Country;
    private String dni;
    private String civil_State;
    private boolean childrens = false;
    public static LinkedList<Hijo> son_info = new LinkedList<Hijo>();
    private String home;
    private String place;
    private int phone;
    private String career;
    private String academic_Level;
    public static LinkedList<Estudios> studies_info = new LinkedList<Estudios>();
    private String id;
    private String job;
    private String departament;
    private String contracting;
    private double salary;
    private String start_Day;
    private int workday;
    private double deduction_Bank = 0;
    private double deduction_Bank_Mount = 0;
    private double deduction_Bank_Percent = 0;
    private double deduction_Hospital = 0;
    private double deduction_Hospital_Mount = 0;
    private double deduction_Hospital_Percent = 0;
    private double deduction_Syndicate = 0;
    private double deduction_Syndicate_Mount = 0;
    private double deduction_Syndicate_Percent = 0;
    private double deduction_debt = 0;
    private double deduction_debt_Mount = 0;
    private double deduction_debt_Percent = 0;
    private double deduction_retention = 0;
    private double deduction_retention_Mount = 0;
    private double deduction_retention_Percent = 0;
    private int antiguedad_years = 0;
    private double antiguedad = 0;
    private double inss = 0;
    private double ir = 0;
    private double total_deductions = 0;
    private double net_to_receive = 0;
    private double inss_patronal = 0;
    private int extra_hours = 0;
    private double extra_hours_amount = 0;
    private double commisions = 0;
    private double total_income = 0;
    private double inatec = 0;
    private double vacations = 0;
    private double bonus = 0;
    private double compensation = 0;
    private String id_inss;

    public Ingresar_Empleado() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
        //this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        Add_Son.setEnabled(false);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/Icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Banner = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        Born_Country = new javax.swing.JTextField();
        Home = new javax.swing.JTextField();
        Civil_State = new javax.swing.JTextField();
        Career = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Place = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Deductions = new javax.swing.JComboBox<>();
        Deduction_Amount = new javax.swing.JButton();
        Deduction_Percent = new javax.swing.JButton();
        End = new javax.swing.JButton();
        Main = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Childrens_Yes = new javax.swing.JCheckBox();
        Childrens_No = new javax.swing.JCheckBox();
        Academic_Level = new javax.swing.JComboBox<>();
        ID = new javax.swing.JTextField();
        Workday = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Departament = new javax.swing.JTextField();
        Job = new javax.swing.JTextField();
        Salary = new javax.swing.JTextField();
        Contracting = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        Studies = new javax.swing.JButton();
        Born_Year = new javax.swing.JFormattedTextField();
        DNI = new javax.swing.JFormattedTextField();
        Add_Son = new javax.swing.JButton();
        Start_Date = new javax.swing.JFormattedTextField();
        Commisions = new javax.swing.JButton();
        Extra_Hours = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ID_INSS = new javax.swing.JFormattedTextField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Nomina Mensual - Ingreso de Empleado");
        setIconImage(getIconImage());
        setResizable(false);

        jScrollPane2.setHorizontalScrollBar(null);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1110, 610));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banner.png"))); // NOI18N
        jPanel1.add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nombre Completo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 152, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Año de Nacimiento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Lugar de Nacimiento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("No. INSS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 152, 80, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Telèfono/Celular");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tiene Hijos");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Direcciòn Domiciliaria");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Lugar");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Profesiòn");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Estudios Realizados");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Estado Civil");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 490, 30));
        jPanel1.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 140, -1));

        Born_Country.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(Born_Country, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 140, -1));
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, 140, -1));
        jPanel1.add(Civil_State, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 140, -1));
        jPanel1.add(Career, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 330, 140, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("No. Empleado");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, -1, -1));
        jPanel1.add(Place, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 140, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Ingresos Extra");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 570, -1, -1));

        Deductions.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Deductions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deducciones Bancarias", "Deducciones Hospitalarias", "Sindicato Laboral", "Deuda Laboral", "Retencion Laboral" }));
        Deductions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeductionsActionPerformed(evt);
            }
        });
        jPanel1.add(Deductions, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, -1, -1));

        Deduction_Amount.setBackground(new java.awt.Color(153, 153, 0));
        Deduction_Amount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Deduction_Amount.setText("Ingresar Monto");
        Deduction_Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deduction_AmountActionPerformed(evt);
            }
        });
        jPanel1.add(Deduction_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 660, 170, -1));

        Deduction_Percent.setBackground(new java.awt.Color(153, 153, 0));
        Deduction_Percent.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Deduction_Percent.setText("Ingresar Porcentaje");
        Deduction_Percent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deduction_PercentActionPerformed(evt);
            }
        });
        jPanel1.add(Deduction_Percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 660, 170, -1));

        End.setBackground(new java.awt.Color(153, 153, 0));
        End.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        End.setText("Guardar");
        End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndActionPerformed(evt);
            }
        });
        jPanel1.add(End, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 750, 170, -1));

        Main.setBackground(new java.awt.Color(153, 102, 0));
        Main.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Main.setText("Volver al menú Principal");
        Main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainActionPerformed(evt);
            }
        });
        jPanel1.add(Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 750, 240, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Nivel Academico");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        Childrens_Yes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Childrens_Yes.setText("Si");
        Childrens_Yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Childrens_YesActionPerformed(evt);
            }
        });
        jPanel1.add(Childrens_Yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, -1, -1));

        Childrens_No.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Childrens_No.setText("No");
        Childrens_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Childrens_NoActionPerformed(evt);
            }
        });
        jPanel1.add(Childrens_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        Academic_Level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Educación Básica", "Bachillerato", "Título Profesional", "Maestría", "Doctorado" }));
        Academic_Level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Academic_LevelActionPerformed(evt);
            }
        });
        jPanel1.add(Academic_Level, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 140, -1));
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 380, 140, -1));
        jPanel1.add(Workday, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, 140, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Departamento");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Fecha de Ingreso");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Jornada Laboral");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Tipo de Contratación");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Salario Mensual");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Cargo Empleado");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));
        jPanel1.add(Departament, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 140, -1));
        jPanel1.add(Job, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 140, -1));
        jPanel1.add(Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 140, -1));

        Contracting.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Determinado", "Indeterminado" }));
        Contracting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContractingActionPerformed(evt);
            }
        });
        jPanel1.add(Contracting, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 140, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image3.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, -1));

        Studies.setBackground(new java.awt.Color(153, 153, 0));
        Studies.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Studies.setText("Ingresar Estudio");
        Studies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudiesActionPerformed(evt);
            }
        });
        jPanel1.add(Studies, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 150, -1));

        try {
            Born_Year.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(Born_Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 140, -1));

        try {
            DNI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-######-####?")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, 140, -1));

        Add_Son.setBackground(new java.awt.Color(153, 153, 0));
        Add_Son.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Add_Son.setText("Añadir");
        Add_Son.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_SonActionPerformed(evt);
            }
        });
        jPanel1.add(Add_Son, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 265, -1, 30));

        try {
            Start_Date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(Start_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 440, 140, -1));

        Commisions.setBackground(new java.awt.Color(153, 153, 0));
        Commisions.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Commisions.setText("Ingresar Comisiones por ventas");
        Commisions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommisionsActionPerformed(evt);
            }
        });
        jPanel1.add(Commisions, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 610, 270, -1));

        Extra_Hours.setBackground(new java.awt.Color(153, 153, 0));
        Extra_Hours.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Extra_Hours.setText("Ingresar Horas Extras");
        Extra_Hours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Extra_HoursActionPerformed(evt);
            }
        });
        jPanel1.add(Extra_Hours, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 660, 210, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Deducciones Laborales");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("No. de Identificador");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, -1, -1));

        try {
            ID_INSS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(ID_INSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, 140, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo2.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainActionPerformed
        Ventana_Principal v = new Ventana_Principal();
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MainActionPerformed

    private void EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndActionPerformed
        try {
            if (Name.getText().isEmpty() | Born_Year.getText().isEmpty() | Born_Country.getText().isEmpty() | DNI.getText().isEmpty() || Civil_State.getText().isEmpty()
                    || Home.getText().isEmpty() || Place.getText().isEmpty() || Phone.getText().isEmpty() || Career.getText().isEmpty() || ID.getText().isEmpty()
                    || Job.getText().isEmpty() || Departament.getText().isEmpty() || Start_Date.getText().isEmpty() || Salary.getText().isEmpty() || Workday.getText().isEmpty()
                    || ID_INSS.getText().isEmpty()) {
                throw new NullPointerException("Ha ocurrido un error");
            } else {
                name = Name.getText();
                born_year = Born_Year.getText();
                born_Country = Born_Country.getText();
                dni = DNI.getText();
                civil_State = Civil_State.getText();
                home = Home.getText();
                place = Place.getText();
                phone = Integer.parseInt(Phone.getText());
                career = Career.getText();
                academic_Level = (String) Academic_Level.getSelectedItem();
                id = ID.getText();
                job = Job.getText();
                departament = Departament.getText();
                start_Day = Start_Date.getText();
                contracting = (String) Contracting.getSelectedItem();
                salary = Double.parseDouble(Salary.getText());
                workday = Integer.parseInt(Workday.getText());
                deduction_Bank = (deduction_Bank_Mount == 0) ? ((deduction_Bank_Percent / 100) * salary) : (deduction_Bank_Mount);
                deduction_Hospital = (deduction_Hospital_Mount == 0) ? ((deduction_Hospital_Percent / 100) * salary) : (deduction_Hospital_Mount);
                deduction_Syndicate = (deduction_Syndicate_Mount == 0) ? ((deduction_Syndicate_Percent / 100) * salary) : (deduction_Syndicate_Mount);
                deduction_debt = (deduction_debt_Mount == 0) ? ((deduction_debt_Percent / 100) * salary) : (deduction_debt_Mount);
                deduction_retention = (deduction_retention_Mount == 0) ? ((deduction_retention_Percent / 100) * salary) : (deduction_retention_Mount);
                antiguedad_years = year - Integer.parseInt(start_Day.substring(6));
                antiguedad = calcularAntiguedad(antiguedad_years, salary);
                extra_hours_amount = (salary / 240) * extra_hours;
                total_income = salary + antiguedad + extra_hours_amount + commisions;
                inss = total_income * 0.0625;
                ir = calcularIR(salary - inss);
                total_deductions = inss + ir + deduction_Bank + deduction_Hospital + deduction_Syndicate + deduction_debt + deduction_retention;
                net_to_receive = total_income - total_deductions;
                inss_patronal = total_income * 0.19;
                inatec = total_income * 0.02;
                vacations = (salary / 30) * 2.5;
                bonus = (salary / 30) * 2.5;
                compensation = (antiguedad > 3) ? ((salary/30)*(20/12)) : ((salary/30)*(30/12));
                id_inss = ID_INSS.getText();
            }

            empleado = new Empleado(name, born_year, born_Country, dni, civil_State, childrens, son_info, home, place, phone, career,
                    academic_Level, studies_info, id, job, departament, contracting, salary, start_Day, workday, deduction_Bank, deduction_Hospital,
                    deduction_Syndicate, deduction_debt, deduction_retention, antiguedad_years, antiguedad, extra_hours, extra_hours_amount, commisions,
                    total_income, inss, ir, total_deductions, net_to_receive, inss_patronal, inatec, vacations, bonus, compensation, id_inss);

            Lista.add(empleado);

            try {
                ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("Empleados.dat"));
                oos.writeObject(Lista);
                oos.close();
                JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (InputMismatchException | NumberFormatException | NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        Ventana_Principal vp = new Ventana_Principal();
        vp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EndActionPerformed

    private void Deduction_AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deduction_AmountActionPerformed
        int op = Deductions.getSelectedIndex();
        try {
            switch (op) {
                case 0:
                    deduction_Bank_Mount = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el monto de la deducción Bancaria", "Ingresar Datos", JOptionPane.INFORMATION_MESSAGE));
                    if (deduction_Bank_Mount < 0) {
                        throw new NumberFormatException("Ha ocurrido un error");
                    }
                    JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    break;

                case 1:
                    deduction_Hospital_Mount = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el monto de la deducción hospitalaria", "Ingresar Datos", JOptionPane.INFORMATION_MESSAGE));
                    if (deduction_Hospital_Mount < 0) {
                        throw new NumberFormatException("Ha ocurrido un error");
                    }
                    JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    break;

                case 2:
                    deduction_Syndicate_Mount = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el monto de la deducción del sindicato laboral", "Ingresar Datos", JOptionPane.INFORMATION_MESSAGE));
                    if (deduction_Syndicate_Mount < 0) {
                        throw new NumberFormatException("Ha ocurrido un error");
                    }
                    JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    break;

                case 3:
                    deduction_debt_Mount = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el monto de la deducción de deuda laboral", "Ingresar Datos", JOptionPane.INFORMATION_MESSAGE));
                    if (deduction_debt_Mount < 0) {
                        throw new NumberFormatException("Ha ocurrido un error");
                    }
                    JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    break;

                case 4:
                    deduction_retention_Mount = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el monto de la deducción de retención laboral", "Ingresar Datos", JOptionPane.INFORMATION_MESSAGE));
                    if (deduction_retention_Mount < 0) {
                        throw new NumberFormatException("Ha ocurrido un error");
                    }
                    JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    break;
            }
        } catch (NumberFormatException | NullPointerException | InputMismatchException e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Deduction_AmountActionPerformed

    private void Deduction_PercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deduction_PercentActionPerformed
        int op = Deductions.getSelectedIndex();
        try {
            switch (op) {
                case 0:
                    deduction_Bank_Percent = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el porcentaje de la deducción Bancaria", "Ingresar Datos", JOptionPane.INFORMATION_MESSAGE));
                    if (deduction_Bank_Percent < 0) {
                        throw new NumberFormatException("Ha ocurrido un error");
                    }
                    JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    break;

                case 1:
                    deduction_Hospital_Percent = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el porcentaje de la deducción hospitalaria", "Ingresar Datos", JOptionPane.INFORMATION_MESSAGE));
                    if (deduction_Hospital_Percent < 0) {
                        throw new NumberFormatException("Ha ocurrido un error");
                    }
                    JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    break;

                case 2:
                    deduction_Syndicate_Percent = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el porcentaje de la deducción del sindicato laboral", "Ingresar Datos", JOptionPane.INFORMATION_MESSAGE));
                    if (deduction_Syndicate_Percent < 0) {
                        throw new NumberFormatException("Ha ocurrido un error");
                    }
                    JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    break;

                case 3:
                    deduction_debt_Percent = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el porcentaje de la deducción de deuda laboral", "Ingresar Datos", JOptionPane.INFORMATION_MESSAGE));
                    if (deduction_debt_Percent < 0) {
                        throw new NumberFormatException("Ha ocurrido un error");
                    }
                    JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    break;

                case 4:
                    deduction_retention_Percent = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el porcentaje de la deducción de retención laboral", "Ingresar Datos", JOptionPane.INFORMATION_MESSAGE));
                    if (deduction_retention_Percent < 0) {
                        throw new NumberFormatException("Ha ocurrido un error");
                    }
                    JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    break;
            }
        } catch (NumberFormatException | NullPointerException | InputMismatchException e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Deduction_PercentActionPerformed

    private void StudiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudiesActionPerformed
        Agregar_Estudios ae = new Agregar_Estudios();
        ae.setVisible(true);
    }//GEN-LAST:event_StudiesActionPerformed

    private void Academic_LevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Academic_LevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Academic_LevelActionPerformed

    private void Childrens_YesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Childrens_YesActionPerformed
        if (Childrens_Yes.isSelected()) {
            Childrens_No.setEnabled(false);
            childrens = true;
            Add_Son.setEnabled(true);
        } else {
            Childrens_No.setEnabled(true);
            childrens = false;
            Add_Son.setEnabled(false);
        }
    }//GEN-LAST:event_Childrens_YesActionPerformed

    private void Childrens_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Childrens_NoActionPerformed
        if (Childrens_No.isSelected()) {
            Childrens_Yes.setEnabled(false);
            childrens = false;
            Add_Son.setEnabled(false);
        } else {
            Childrens_Yes.setEnabled(true);
            childrens = false;
            Add_Son.setEnabled(false);
        }
    }//GEN-LAST:event_Childrens_NoActionPerformed

    private void ContractingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContractingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContractingActionPerformed

    private void DeductionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeductionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeductionsActionPerformed

    private void Add_SonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_SonActionPerformed
        Agregar_Hijos ah = new Agregar_Hijos();
        ah.setVisible(true);
    }//GEN-LAST:event_Add_SonActionPerformed

    private void CommisionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommisionsActionPerformed
        try {
            commisions = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las comisiones por ventas", "Ingresar Datos", JOptionPane.INFORMATION_MESSAGE));
            if (commisions < 0) {
                throw new NumberFormatException("Ha ocurrido un error");
            }
            JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException | InputMismatchException | NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CommisionsActionPerformed

    private void Extra_HoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Extra_HoursActionPerformed
        try {
            extra_hours = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las horas extras realizadas", "Ingresar Datos", JOptionPane.INFORMATION_MESSAGE));
            if (extra_hours < 0) {
                throw new NumberFormatException("Ha ocurrido un error");
            }
            JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException | InputMismatchException | NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Extra_HoursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar_Empleado().setVisible(true);
            }
        });
    }

    public double calcularAntiguedad(int x, double y) {
        switch (x) {
            case 0:
                return 0;
            case 1:
                return y * 0.03;
            case 2:
                return y * 0.05;
            case 3:
                return y * 0.07;
            case 4:
                return y * 0.09;
            case 5:
                return y * 0.1;
            case 6:
                return y * 0.11;
            case 7:
                return y * 0.012;
            case 8:
                return y * 0.13;
            case 9:
                return y * 0.14;
            case 10:
                return y * 0.15;
            case 11:
                return y * 0.155;
            case 12:
                return y * 0.16;
            case 13:
                return y * 0.165;
            case 14:
                return y * 0.17;
            case 15:
                return y * 0.175;
            case 16:
                return y * 0.18;
            case 17:
                return y * 0.185;
            case 18:
                return y * 0.19;
            case 19:
                return y * 0.195;
            default:
                return y * 0.2;
        }
    }

    private double calcularIR(double x) {
        double y = x * 12;

        if (y > 0 && y < 100001) {
            return 0;
        } else {
            if (y > 100000 && y < 200001) {
                return ((y - 100000) * 0.15) / 12;
            } else {
                if (y > 200000 && y < 350001) {
                    return (((y - 200000) * 0.2) + 15000) / 12;
                } else {
                    if (y > 350000 && y < 500001) {
                        return (((y - 350000) * 0.25) + 45000) / 12;
                    } else {
                        return (((y - 500000) * 0.3) + 82500) / 12;
                    }
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Academic_Level;
    private javax.swing.JButton Add_Son;
    private javax.swing.JLabel Banner;
    private javax.swing.JTextField Born_Country;
    private javax.swing.JFormattedTextField Born_Year;
    private javax.swing.JTextField Career;
    private javax.swing.JCheckBox Childrens_No;
    private javax.swing.JCheckBox Childrens_Yes;
    private javax.swing.JTextField Civil_State;
    private javax.swing.JButton Commisions;
    private javax.swing.JComboBox<String> Contracting;
    private javax.swing.JFormattedTextField DNI;
    private javax.swing.JButton Deduction_Amount;
    private javax.swing.JButton Deduction_Percent;
    private javax.swing.JComboBox<String> Deductions;
    private javax.swing.JTextField Departament;
    private javax.swing.JButton End;
    private javax.swing.JButton Extra_Hours;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField Home;
    private javax.swing.JTextField ID;
    private javax.swing.JFormattedTextField ID_INSS;
    private javax.swing.JTextField Job;
    private javax.swing.JButton Main;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField Place;
    private javax.swing.JTextField Salary;
    private javax.swing.JFormattedTextField Start_Date;
    private javax.swing.JButton Studies;
    private javax.swing.JTextField Workday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
