package Interfaces;

import Classes.Empleado;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 * @author Chaphloziferar
 **/

public class Ventana_Principal extends javax.swing.JFrame {
    
    public Ventana_Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
        
        File file = new File("Empleados.dat");
        
        if(file.exists()){
            try{
                ObjectInputStream ois = new  ObjectInputStream(new FileInputStream("Empleados.dat"));
                Ingresar_Empleado.Lista = (LinkedList<Empleado>) ois.readObject();
                ois.close();
            }catch(IOException | ClassNotFoundException e){
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/Icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ingresar_Empleado_BTN = new javax.swing.JButton();
        Mostrar_Nomina = new javax.swing.JButton();
        Buscar_Empleado = new javax.swing.JButton();
        Eliminar_Empleado = new javax.swing.JButton();
        Asiento_Contable = new javax.swing.JButton();
        Image1 = new javax.swing.JLabel();
        Image2 = new javax.swing.JLabel();
        Image3 = new javax.swing.JLabel();
        Banner = new javax.swing.JLabel();
        Generar_Informe = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de nómina mensual");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ingresar_Empleado_BTN.setBackground(new java.awt.Color(204, 153, 0));
        Ingresar_Empleado_BTN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Ingresar_Empleado_BTN.setText("Ingresar Empleado");
        Ingresar_Empleado_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar_Empleado_BTNActionPerformed(evt);
            }
        });
        getContentPane().add(Ingresar_Empleado_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 230, 40));

        Mostrar_Nomina.setBackground(new java.awt.Color(204, 153, 0));
        Mostrar_Nomina.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Mostrar_Nomina.setText("Mostrar Nómina");
        Mostrar_Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_NominaActionPerformed(evt);
            }
        });
        getContentPane().add(Mostrar_Nomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 230, 40));

        Buscar_Empleado.setBackground(new java.awt.Color(204, 153, 0));
        Buscar_Empleado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Buscar_Empleado.setText("Buscar Empleado");
        Buscar_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_EmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar_Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 230, 40));

        Eliminar_Empleado.setBackground(new java.awt.Color(204, 153, 0));
        Eliminar_Empleado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Eliminar_Empleado.setText("Eliminar Empleado");
        Eliminar_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_EmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar_Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 230, 40));

        Asiento_Contable.setBackground(new java.awt.Color(204, 153, 0));
        Asiento_Contable.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Asiento_Contable.setText("Asiento Contable");
        Asiento_Contable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asiento_ContableActionPerformed(evt);
            }
        });
        getContentPane().add(Asiento_Contable, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 220, 40));

        Image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image1.png"))); // NOI18N
        getContentPane().add(Image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        Image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image2.png"))); // NOI18N
        getContentPane().add(Image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, -1, -1));

        Image3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image4.png"))); // NOI18N
        getContentPane().add(Image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Banner.png"))); // NOI18N
        getContentPane().add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 120));

        Generar_Informe.setBackground(new java.awt.Color(204, 153, 0));
        Generar_Informe.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Generar_Informe.setText("Generar Informe");
        Generar_Informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generar_InformeActionPerformed(evt);
            }
        });
        getContentPane().add(Generar_Informe, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 220, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ingresar_Empleado_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar_Empleado_BTNActionPerformed
        Ingresar_Empleado ie = new Ingresar_Empleado();
        ie.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Ingresar_Empleado_BTNActionPerformed

    private void Mostrar_NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_NominaActionPerformed
        Mostrar_Empleados me = new Mostrar_Empleados();
        me.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Mostrar_NominaActionPerformed

    private void Buscar_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_EmpleadoActionPerformed
        Ventana_Busqueda_Data b = new Ventana_Busqueda_Data();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Buscar_EmpleadoActionPerformed

    private void Eliminar_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_EmpleadoActionPerformed
        Ventana_Eliminar_Data e = new Ventana_Eliminar_Data();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Eliminar_EmpleadoActionPerformed

    private void Asiento_ContableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asiento_ContableActionPerformed
        Ventana_Asiento va = new Ventana_Asiento();
        va.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Asiento_ContableActionPerformed

    private void Generar_InformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generar_InformeActionPerformed
        Ventana_Informe_Data i = new Ventana_Informe_Data();
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Generar_InformeActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Asiento_Contable;
    private javax.swing.JLabel Banner;
    private javax.swing.JButton Buscar_Empleado;
    private javax.swing.JButton Eliminar_Empleado;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Generar_Informe;
    private javax.swing.JLabel Image1;
    private javax.swing.JLabel Image2;
    private javax.swing.JLabel Image3;
    private javax.swing.JButton Ingresar_Empleado_BTN;
    private javax.swing.JButton Mostrar_Nomina;
    // End of variables declaration//GEN-END:variables
}
