/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.Empleado;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PC 2
 */
public class Ventana_Informe_Data extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Informe_Data
     */
    public Ventana_Informe_Data() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/Icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Opcion = new javax.swing.JComboBox<>();
        Dato_Buscar = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        End = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Búsqueda");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Opcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre Completo", "No. Empleado", "No. Cédula", "No. INSS" }));
        getContentPane().add(Opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 160, 33));

        Dato_Buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Dato_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 320, 40));

        Search.setBackground(new java.awt.Color(153, 153, 0));
        Search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Search.setText("Buscar Empleado");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 155, 33));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image5.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image6.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        End.setBackground(new java.awt.Color(153, 102, 0));
        End.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        End.setText("Cerrar Ventana");
        End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndActionPerformed(evt);
            }
        });
        getContentPane().add(End, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 130, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo3.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        if (Dato_Buscar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe llenar el formulario", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            LinkedList<Empleado> buscado = buscarEmpleado();
            if (buscado == null) {
                JOptionPane.showMessageDialog(null, "No se encontró ningún resultado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } else {
                Ventana_Informe vi = new Ventana_Informe();
                vi.e = buscado.getFirst();
                vi.setVisible(true);
                vi.generarDatos();
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndActionPerformed
        Ventana_Principal vp = new Ventana_Principal();
        vp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Informe_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Informe_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Informe_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Informe_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Informe_Data().setVisible(true);
            }
        });
    }

    
    public LinkedList<Empleado> buscarEmpleado() {
        int pos = -1, op = Opcion.getSelectedIndex();
        String dato = Dato_Buscar.getText();
        LinkedList<Empleado> search_result = new LinkedList<>();

        switch (op) {
            case 0:
                for (Empleado e : Ingresar_Empleado.Lista) {
                    if (e.getName().equalsIgnoreCase(dato)) {
                        pos = Ingresar_Empleado.Lista.indexOf(e);
                        search_result.add(Ingresar_Empleado.Lista.get(pos));
                    }
                }
                if (pos == -1) {
                    search_result = null;
                }
                break;

            case 1:
                for (Empleado e : Ingresar_Empleado.Lista) {
                    if (e.getID().equalsIgnoreCase(dato)) {
                        pos = Ingresar_Empleado.Lista.indexOf(e);
                        search_result.add(Ingresar_Empleado.Lista.get(pos));
                    }
                }
                if (pos == -1) {
                    search_result = null;
                }
                break;

            case 2:
                for (Empleado e : Ingresar_Empleado.Lista) {
                    if (e.getDNI().equalsIgnoreCase(dato)) {
                        pos = Ingresar_Empleado.Lista.indexOf(e);
                        search_result.add(Ingresar_Empleado.Lista.get(pos));
                    }
                }
                if (pos == -1) {
                    search_result = null;
                }
                break;
                    
            case 3:
                for (Empleado e : Ingresar_Empleado.Lista) {
                    if (e.getID_INSS().equalsIgnoreCase(dato)) {
                        pos = Ingresar_Empleado.Lista.indexOf(e);
                        search_result.add(Ingresar_Empleado.Lista.get(pos));
                    }
                }
                if (pos == -1) {
                    search_result = null;
                }
                break;
        }
        return search_result;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dato_Buscar;
    private javax.swing.JButton End;
    private javax.swing.JLabel Fondo;
    private javax.swing.JComboBox<String> Opcion;
    private javax.swing.JButton Search;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
