/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.Empleado;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author PC 2
 */
public class Ventana_Informe extends javax.swing.JFrame {

    public Empleado e;

    public Ventana_Informe() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/Icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ID_Empleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Job = new javax.swing.JTextField();
        Contracting = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Datos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Salary = new javax.swing.JTextField();
        Antiguedad = new javax.swing.JTextField();
        Total_Ordinary = new javax.swing.JTextField();
        Extra_Hours = new javax.swing.JTextField();
        Commisions = new javax.swing.JTextField();
        Total_Extraordinary = new javax.swing.JTextField();
        Net_Pay = new javax.swing.JTextField();
        Inss_Patronal = new javax.swing.JTextField();
        Vacations = new javax.swing.JTextField();
        Bonus = new javax.swing.JTextField();
        Compensation = new javax.swing.JTextField();
        Total_Prestations = new javax.swing.JTextField();
        Total_Income = new javax.swing.JTextField();
        Total_Deduction = new javax.swing.JTextField();
        Print = new javax.swing.JButton();
        End1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Nomina Mensual - Informe de Ingresos y Egresos");
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Informe de Ingresos y Egresos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nombre Completo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 79, -1, -1));

        Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 310, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("No. Empleado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        ID_Empleado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(ID_Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 147, 37));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Cargo Empleado");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tipo de contratación");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        Job.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(Job, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 230, 37));

        Contracting.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(Contracting, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 147, 37));

        Tabla_Datos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tabla_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Cotización INSS", null},
                {"Cotización IR", null},
                {"Préstamos Bancarios", null},
                {"Deducción Hospitalaria", null},
                {"Sindicato Laboral", null},
                {"Deuda Laboral", null},
                {"Retención Laboral", null},
                {"Total Deduciones", null}
            },
            new String [] {
                "Deducciones", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla_Datos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 597, 120));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Ingreso Básico");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 127, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Antiguedad");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Total Ordinario");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 130, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Horas Extras");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Comisiones por Ventas");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Total Deducciones");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Vacaciones");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("INSS Patronal");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, -1, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Treceavo Mes");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Indemnización");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Total Prestaciones");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Total Extraordinario");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Total Ingresos");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Neto Pagado");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, -1, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("C$");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, 30, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("C$");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 352, 30, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("C$");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 30, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("C$");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 30, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("C$");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 30, 20));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("C$");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 30, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("C$");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 30, 20));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("C$");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 30, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("C$");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 30, 20));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("C$");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 30, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("C$");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 30, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setText("C$");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 30, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setText("C$");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 30, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setText("C$");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 30, -1));
        jPanel1.add(Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 80, 30));
        jPanel1.add(Antiguedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 80, 30));
        jPanel1.add(Total_Ordinary, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 80, 30));
        jPanel1.add(Extra_Hours, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 80, 30));
        jPanel1.add(Commisions, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 80, 30));
        jPanel1.add(Total_Extraordinary, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 80, 30));
        jPanel1.add(Net_Pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, 80, 30));
        jPanel1.add(Inss_Patronal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 80, 30));
        jPanel1.add(Vacations, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 80, 30));
        jPanel1.add(Bonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 80, 30));
        jPanel1.add(Compensation, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 80, 30));
        jPanel1.add(Total_Prestations, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 80, 30));
        jPanel1.add(Total_Income, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 80, 30));
        jPanel1.add(Total_Deduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 80, 30));

        Print.setBackground(new java.awt.Color(153, 153, 0));
        Print.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Print.setText("Imprimir ");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel1.add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 670, 150, 30));

        End1.setBackground(new java.awt.Color(153, 102, 0));
        End1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        End1.setText("Volver al menú");
        End1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                End1ActionPerformed(evt);
            }
        });
        jPanel1.add(End1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 670, 150, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo4.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        JOptionPane.showMessageDialog(null, "No se detecta impresora conectada", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_PrintActionPerformed

    private void End1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_End1ActionPerformed
        Ventana_Principal vp = new Ventana_Principal();
        vp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_End1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Informe().setVisible(true);
            }
        });
    }

    public void generarDatos() {

        DecimalFormat decimales = new DecimalFormat("0.00");

        Name.setEnabled(false);
        Name.setText(e.getName());
        ID_Empleado.setEnabled(false);
        ID_Empleado.setText(e.getID());
        Job.setEnabled(false);
        Job.setText(e.getJob());
        Contracting.setEnabled(false);
        Contracting.setText(e.getContracting());

        Tabla_Datos.setValueAt(decimales.format(e.getINSS()), 0, 1);
        Tabla_Datos.setValueAt(decimales.format(e.getIR()), 1, 1);
        Tabla_Datos.setValueAt(decimales.format(e.getDeduction_Bank()), 2, 1);
        Tabla_Datos.setValueAt(decimales.format(e.getDeduction_Hospital()), 3, 1);
        Tabla_Datos.setValueAt(decimales.format(e.getDeduction_Syndicate()), 4, 1);
        Tabla_Datos.setValueAt(decimales.format(e.getDeduction_debt()), 5, 1);
        Tabla_Datos.setValueAt(decimales.format(e.getDeduction_debt()), 6, 1);
        Tabla_Datos.setValueAt(decimales.format(e.getTotal_Deductions()), 7, 1);
        
        ((DefaultTableCellRenderer) Tabla_Datos.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        Tabla_Datos.getColumnModel().getColumn(0).setCellRenderer(tcr);
        Tabla_Datos.getColumnModel().getColumn(1).setCellRenderer(tcr);

        Salary.setText(String.valueOf(e.getSalary()));
        Antiguedad.setText(String.valueOf(decimales.format(e.getAntiguedad())));
        Total_Ordinary.setText(String.valueOf(decimales.format(e.getSalary() + e.getAntiguedad())));

        Extra_Hours.setText(String.valueOf(decimales.format(e.getExtra_Hours_Amount())));
        Commisions.setText(String.valueOf(decimales.format(e.getCommisions())));
        Total_Extraordinary.setText(String.valueOf(decimales.format(e.getExtra_Hours_Amount() + e.getCommisions())));

        Vacations.setText(String.valueOf(decimales.format(e.getVacations())));
        Bonus.setText(String.valueOf(decimales.format(e.getBonus())));
        Compensation.setText(String.valueOf(decimales.format(e.getCompensation())));
        Total_Prestations.setText(String.valueOf(decimales.format(e.getVacations() + e.getBonus() + e.getCompensation())));

        Total_Income.setText(String.valueOf(decimales.format(e.getTotal_Income())));
        Total_Deduction.setText(String.valueOf(decimales.format(e.getTotal_Deductions())));
        Net_Pay.setText(String.valueOf(decimales.format(e.getNet_To_Receive())));
        Inss_Patronal.setText(String.valueOf(decimales.format(e.getINSS_Patronal())));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Antiguedad;
    private javax.swing.JTextField Bonus;
    private javax.swing.JTextField Commisions;
    private javax.swing.JTextField Compensation;
    private javax.swing.JTextField Contracting;
    private javax.swing.JButton End1;
    private javax.swing.JTextField Extra_Hours;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField ID_Empleado;
    private javax.swing.JTextField Inss_Patronal;
    private javax.swing.JTextField Job;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Net_Pay;
    private javax.swing.JButton Print;
    private javax.swing.JTextField Salary;
    private javax.swing.JTable Tabla_Datos;
    private javax.swing.JTextField Total_Deduction;
    private javax.swing.JTextField Total_Extraordinary;
    private javax.swing.JTextField Total_Income;
    private javax.swing.JTextField Total_Ordinary;
    private javax.swing.JTextField Total_Prestations;
    private javax.swing.JTextField Vacations;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
